version: "3"

services:
    db:
        container_name: pg_container2
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: api_prenatal
        ports:
            - "15432:5432"

    pgadmin:
        container_name: pgadmin4_container2
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
