version: "3"

services:
    app:
      build: .
      command: yarn dev:start
      ports:
        - "3333:3333"
      volumes:
        - .:/user/app

    teste-postgres-compose:
      image: postgres
      environment:
        POSTGRES_PASSWORD: "teste"
      ports:
          - "15432:5432"
      volumes:
           - /user/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
      networks:
           - postgres-compose-network

    teste-pgadmin-compose:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "alvaro@hotmail.com"
        PGADMIN_DEFAULT_PASSWORD: "teste"
      ports:
        - "16543:80"
      depends_on:
        - teste-postgres-compose
      networks:
        - postgres-compose-network

    networks:
      postgres-compose-network:
        driver: bridge
